DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (ID LONG AUTO_INCREMENT PRIMARY KEY, NUMERODEMATRICULA VARCHAR(20) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

-- para test --
INSERT INTO ODONTOLOGOS(NUMERODEMATRICULA, NOMBRE, APELLIDO) VALUES ('123456789', 'Pepito', 'Perez'), ('987654321', 'Margarita','Arias');